const gifts = [
  "Baby bottle",
  "Diapers",
  "Baby wipes",
  "Pacifiers",
  "Baby blanket",
  "Crib sheets",
  "Baby clothes",
  "Swaddle blanket",
  "Baby lotion",
  "Baby shampoo",
  "Baby monitor",
  "Changing pad",
  "Diaper bag",
  "Burp cloths",
  "Bib set",
  "Baby socks",
  "Baby shoes",
  "Teething toys",
  "Stuffed animal",
  "Nursing pillow",
  "Bottle warmer",
  "Formula container",
  "Bath toys",
  "Baby towels",
  "Hooded towel",
  "Baby washcloths",
  "Thermometer",
  "Nail clipper set",
  "Baby brush",
  "Baby comb",
  "Car seat",
  "Stroller",
  "High chair",
  "Baby swing",
  "Play mat",
  "Baby carrier",
  "Rocking chair",
  "Night light",
  "Sound machine",
  "Baby books"
  // Continue adding gifts until you reach 200+
];

export default gifts;
